config/routes.rb
Rails.application.routes.draw do
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#home"

  resources :users, only: %i[new create]
  resources :cards, only: %i[index new create edit update destroy]
  resources :decks do
    resources :deck_cards, only: %i[index create destroy]
  end
  resources :public_decks, only: %i[index]
  resources :quiz_sessions, only: %i[index create show destroy] do
    member do
      post :start
      get :question
      post :answer
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  skip_before_action :require_login, only: %i[home]
  def home; end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/home.html.erb
<% set_meta_tags title: nil, og: { title: t(".title") } %>
<div class="page-container mt-24 mb-18 md:mb-8 px-6 md:px-10 lg:px-16 py-4 md:py-8">
  <h1 class="font-bold text-4xl md:text-5xl"><%= t(".title") %></h1>
  <p class="text-indigo-500 text-lg md:text-xl mt-2"><%= t(".info") %></p>
  <div class="flex">
    <div class="[counter-reset:section]">
    <h2 class="font-bold text-2xl md:text-3xl mt-4 mb-2"><%= t(".how_to_use.title") %></h2>
    <div class="home-timeline">
      <h3 class="font-bold"><%= t(".how_to_use.step1.title") %></h3>
      <span class="text-violet-950">
        <%= t(".how_to_use.step1.content_html", signup: link_to(t("defaults.signup"), new_user_path, class: "text-indigo-500 border-b border-dashed") ) %>
      </span>
    </div>
    <div class="home-timeline">
      <h3 class="font-bold"><%= t(".how_to_use.step2.title") %></h3>
      <span class="text-violet-950">
        <%= t(".how_to_use.step2.content_html", create_card: link_to(t("defaults.create_card"), new_card_path, class: "text-indigo-500 border-b border-dashed") ) %>
      </span>
    </div>
    <div class="home-timeline">
      <h3 class="font-bold"><%= t(".how_to_use.step3.title") %></h3>
      <span class="text-violet-950">
        <%= t(".how_to_use.step3.content_html", create_deck: link_to(t("defaults.create_deck"), new_deck_path, class: "text-indigo-500 border-b border-dashed") ) %>
      </span>
    </div>
    <div class="home-timeline">
      <h3 class="font-bold"><%= t(".how_to_use.step4.title") %></h3>
      <span class="text-violet-950">
        <%= t(".how_to_use.step4.content_html", public_decks: link_to(t("defaults.public_decks"), public_decks_path, class: "text-indigo-500 border-b border-dashed") ) %>
      </span>
    </div>
    <div class="home-timeline">
      <h3 class="font-bold"><%= t(".how_to_use.step5.title") %></h3>
      <span class="text-violet-950">
        <%= t(".how_to_use.step5.content_html", public_decks: link_to(t("defaults.public_decks"), public_decks_path, class: "text-indigo-500 border-b border-dashed") ) %>
      </span>
    </div>
    <div class="home-timeline">
      <h3 class="font-bold"><%= t(".how_to_use.step6.title") %></h3>
      <span class="text-violet-950">
        <%= t(".how_to_use.step6.content_html", quiz: link_to(t("defaults.quiz"), quiz_sessions_path, class: "text-indigo-500 border-b border-dashed") ) %>
      </span>
    </div>
    </div>
    <%= image_tag "icon.png", size: '400x100', class: "hidden lg:block pl-16" %>
  </div>
</div>