config/routes.rb
Rails.application.routes.draw do
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#home"

  resources :users, only: %i[new create]
  resources :cards, only: %i[index new create edit update destroy]
  resources :decks do
    resources :deck_cards, only: %i[index create destroy]
  end
  resources :public_decks, only: %i[index]
  resources :quiz_sessions, only: %i[index create show destroy] do
    member do
      post :start
      get :question
      post :answer
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :card
  belongs_to :quiz_session
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/card.rb
class Card < ApplicationRecord
  validates :name, presence: true, length: { maximum: 18 }
  validates :meaning, presence: true, length: { maximum: 54 }

  belongs_to :user
  has_many :deck_cards, dependent: :destroy
  has_many :decks, through: :deck_cards
  has_many :answers, dependent: :destroy
end

app/models/deck.rb
class Deck < ApplicationRecord
  validates :name, presence: true, length: { maximum: 36 }
  validates :description, length: { maximum: 72 }
  validates :public, inclusion: [ true, false ]

  belongs_to :user
  has_many :deck_cards, dependent: :destroy
  has_many :cards, through: :deck_cards
  has_many :quiz_sessions, dependent: :destroy
end

app/models/deck_card.rb
class DeckCard < ApplicationRecord
  belongs_to :deck
  belongs_to :card

  validates :deck_id, uniqueness: { scope: :card_id }
end

app/models/quiz_session.rb
class QuizSession < ApplicationRecord
  belongs_to :user
  belongs_to :deck
  has_many :answers, dependent: :destroy

  enum status: { pending: 0, in_progress: 1, completed: 2 }

  def answered_cards_ids
    # 既に回答したカードのIDリスト
    self.answers.pluck(:card_id)
  end

  def unanswered_cards
    # まだ回答していないカードを取得するメソッド
    self.deck.cards.where.not(id: answered_cards_ids)
  end

  def random_card
    # ランダムなカードを出題するインスタンスメソッド
    # まだ回答していないカードから出題する

    # カード数が少ない場合はRubyの配列のメソッドであるsampleメソッドで実装してもいい
    # unanswered_cards.sample
    unanswered_cards.order(Arel.sql("RANDOM()")).first
  end

  def answered_count
    # 回答した問題数
    self.answers.count
  end

  def all_answered?
    answered_count >= self.total_questions
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name, presence: true, length: { minimum: 2, maximum: 20 }
  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :password, confirmation: true, length: { minimum: 8 }

  has_many :cards, dependent: :destroy
  has_many :decks, dependent: :destroy
  has_many :quiz_sessions, dependent: :destroy
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = current_user.cards
  end

  def new
    @card = Card.new
  end

  def create
    @card = current_user.cards.build(card_params)
    if @card.save
      redirect_to cards_path, notice: t("defaults.flash_message.created", item: Card.model_name.human)
    else
      flash.now[:alert] = t("defaults.flash_message.not_created", item: Card.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  # Cardの詳細ページは現状不要なのでルーティングから除外した
  # 今後使用するかもしれないのでコードは残す
  # def show
  #   @card = current_user.cards.find(params[:id])
  # end

  def edit
    @card = current_user.cards.find(params[:id])
  end

  def update
    @card = current_user.cards.find(params[:id])
    if @card.update(card_params)
      redirect_to cards_path, notice: t("defaults.flash_message.updated", item: Card.model_name.human)
    else
      flash.now[:alert] = t("defaults.flash_message.not_updated", item: Card.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    card = current_user.cards.find(params[:id])
    card.destroy!
    redirect_to cards_path, status: :see_other, notice: t("defaults.flash_message.deleted", item: Card.model_name.human)
  end

  private

  def card_params
    params.require(:card).permit(:name, :meaning)
  end
end

app/controllers/deck_cards_controller.rb
class DeckCardsController < ApplicationController
  before_action :set_deck

  def index
    @cards = current_user.cards.where.not(id: @deck.card_ids)
  end

  def create
    @card = Card.find(params[:card_id])
    @deck.cards << @card

    redirect_to deck_deck_cards_path(@deck), notice: t("defaults.flash_message.added", item: Card.model_name.human)
  end

  def destroy
    @deck_card = @deck.deck_cards.find(params[:id])
    @deck_card.destroy!
    redirect_to deck_path(@deck), status: :see_other, notice: t("defaults.flash_message.delete_from_deck")
  end

  private

  def set_deck
    @deck = Deck.find(params[:deck_id])
  end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index
    @decks = current_user.decks
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = current_user.decks.build(deck_params)
    if @deck.save
      redirect_to deck_path(@deck), notice: t("defaults.flash_message.created", item: Deck.model_name.human)
    else
      flash.now[:alert] = t("defaults.flash_message.not_created", item: Deck.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @deck = current_user.decks.find(params[:id])
  end

  def edit
    @deck = current_user.decks.find(params[:id])
  end

  def update
    @deck = current_user.decks.find(params[:id])
    if @deck.update(deck_params)
      redirect_to deck_path(@deck), notice: t("defaults.flash_message.updated", item: Deck.model_name.human)
    else
      flash.now[:alert] = t("defaults.flash_message.not_updated", item: Card.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    deck = current_user.decks.find(params[:id])
    deck.destroy!
    redirect_to decks_path, status: :see_other, notice: t("defaults.flash_message.deleted", item: Deck.model_name.human)
  end

  private

  def deck_params
    params.require(:deck).permit(:name, :description, :public)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: %i[new create]
  before_action :redirect_after_login, only: %i[new]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: t(".success")
    else
      flash.now[:alert] = t(".failure")
      render :new, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def default_meta_tags
    {
      site: "Flashare",
      title: "フラッシュカードを作成してシェアできるサービス",
      reverse: true,
      charset: "utf-8",
      description: "Flashareはカードを作成・解答して、作成したデッキを任意で公開できるフラッシュカードアプリです。",
      canonical: request.original_url,
      separator: "|",
      og: {
        site_name: :site,
        title: :title,
        description: :description,
        type: "website",
        url: request.original_url,
        image: image_url("ogp.png"),
        local: "ja-JP"
      },
      twitter: {
        card: "summary_large_image",
        site: "@karume_Ao"
      }
    }
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/deck_cards_helper.rb
module DeckCardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/helpers/public_decks_helper.rb
module PublicDecksHelper
end

app/helpers/quiz_sessions_helper.rb
module QuizSessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <%= favicon_link_tag 'icon.png' %>
    <%# <link rel="icon" href="/icon.svg" type="image/svg+xml"> %>
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= display_meta_tags(default_meta_tags) %> 
    <meta name="theme-color" content="#ffffff" media="(prefers-color-scheme: light)">
    <meta name="theme-color" content="#000000" media="(prefers-color-scheme: dark)">
    <script src="https://kit.fontawesome.com/cb2bbb68d1.js" crossorigin="anonymous"></script>
  </head>

  <body class="flex flex-col min-h-screen bg-linear-to-r from-blue-500/60 to-violet-500/60 text-indigo-800">
    <% if logged_in? %>
      <%= render 'shared/header' %>
    <% else %>
      <%= render 'shared/before_login_header' %>
    <% end %>
    <%= render 'shared/flash_message' %>
    <main class="grow container mx-auto px-4">
      <%= yield %>
    </main>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/shared/_before_login_header.html.erb
<header class="flex justify-between fixed top-0 right-0 w-full p-4 text-lime-50 bg-linear-to-r from-blue-500/90 to-violet-500/90">
  <h1 class="text-2xl">
    <%= link_to root_path, class: "flex items-center gap-1" do %>
      <%= image_tag "icon.png", size: '28x28' %> <span>Flashare</span>
    <% end %>
  </h1>
  <ul class="flex items-center gap-4">
    <li>
      <%= link_to new_user_path do %>
        <i class="fa-solid fa-user-plus"></i> <%= t("defaults.signup") %>
      <% end %>
    </li>
    <li>
      <%= link_to login_path do %>
        <i class="fa-solid fa-user"></i> <%= t("defaults.login") %>
      <% end %>
    </li>
  </ul>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul class="text-red-500">
    <% object.errors.each do |error| %>
      <li><%= error.full_message %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="fixed top-17 right-0 left-0 mx-auto h-8 text-white" data-controller="removals" data-action="animationend->removals#remove">
    <% if message_type == "notice" %>
      <p class="bg-linear-to-r from-green-500 to-teal-500 text-center animate-fade-out">
        <i class="fa-regular fa-thumbs-up"></i> <%= message %>
      </p>
    <% else %>
      <p class="bg-linear-to-r from-red-500 to-rose-600 text-center animate-fade-out">
        <i class="fa-solid fa-circle-exclamation"></i> <%= message %>
      </p>
    <% end %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<%# モバイルデバイスのフッター %>
<footer class="md:hidden fixed bottom-0 z-10 w-full text-lime-50 bg-linear-to-r from-blue-500/90 to-violet-500/90">
  <ul class="grid grid-cols-5 gap-1 py-2">
    <li class="">
      <%= link_to root_path, class: "flex flex-col justify-center items-center" do %>
        <span class="text-xl">
          <i class="fa-regular fa-house"></i>
        </span>
        <span class="text-xs">
          <%= t("defaults.home") %>
        </span>
      <% end %>
    </li>
    <li>
      <%= link_to cards_path, class: "flex flex-col justify-center items-center" do %>
        <span class="text-xl">
          <i class="fa-regular fa-file"></i>
        </span>
        <span class="text-xs">
          <%= t("defaults.cards") %>
        </span>
      <% end %>
    </li>
    <li>
      <%= link_to decks_path, class: "flex flex-col justify-center items-center" do %>
        <span class="text-xl">
          <i class="fa-regular fa-folder"></i>
        </span>
        <span class="text-xs">
          <%= t("defaults.my_decks") %>
        </span>
      <% end %>
    </li>
    <li>
      <%= link_to public_decks_path, class: "flex flex-col justify-center items-center" do %>
        <span class="text-xl">
          <i class="fa-regular fa-folder-open"></i>
        </span>
        <span class="text-xs">
          <%= t("defaults.public_decks") %>
        </span>
      <% end %>
    </li>
    <li>
      <%= link_to quiz_sessions_path, class: "flex flex-col justify-center items-center" do %>
        <span class="text-xl">
          <i class="fa-regular fa-circle-question"></i>
        </span>
        <span class="text-xs">
          <%= t("defaults.quiz") %>
        </span>
      <% end %>
    </li>
  </ul>
</footer>

<%# タブレット・PCのフッター %>
<footer class="hidden md:block">
  <div class="text-sm text-center">
    &copy; 2026 Flashare by karume
  </div>
</footer>

app/views/shared/_header.html.erb
<header class="flex justify-between fixed top-0 right-0 z-20 w-full h-16 p-4 text-lime-50 bg-linear-to-r from-blue-500/90 to-violet-500/90" data-controller="hamburger">
  <h1 class="text-2xl">
    <%= link_to root_path, class: "flex items-center gap-1" do %>
      <%= image_tag "icon.png", size: '28x28' %> <span>Flashare</span>
    <% end %>
  </h1>
  <%# ハンバーガーメニュー %>
  <div class="w-12.5 h-12.5 fixed top-1.25 right-2.5 z-40" data-action="click->hamburger#switchMenu">
    <span class="top-4 w-7.5 h-0.75 bg-lime-50 inline-block absolute left-2.5 transition-all duration-400" data-hamburger-target="hamburgerLine1"></span>
    <span class="top-6.25 w-7.5 h-0.75 bg-lime-50 inline-block absolute left-2.5 transition-all duration-400" data-hamburger-target="hamburgerLine2"></span>
    <span class="top-8.5 w-7.5 h-0.75 bg-lime-50 inline-block absolute left-2.5 transition-all duration-400" data-hamburger-target="hamburgerLine3"></span>
  </div>
  <%# モバイルで展開されるナビゲーションメニュー %>
  <nav class="md:hidden text-lime-50 w-4/5 h-screen bg-linear-to-r from-blue-600 to-violet-600 fixed top-0 -right-4/5 z-30 transition-all duration-600 text-left text-xl" data-hamburger-target="hamburgerMenuMobile">
    <ul class="py-15">
      <li class="pl-8 py-2.5">
        <%= link_to "#" do %>
          <i class="fa-solid fa-circle-info"></i><%= t("defaults.terms_of_use") %>
        <% end %>
      </li>
      <li class="pl-8 py-2.5">
        <%= link_to "#" do %>
          <i class="fa-solid fa-circle-info"></i><%= t("defaults.privacy_policy") %>
        <% end %>
      </li>
    </ul>
    <div class="pl-8">
      <%= link_to logout_path, data: { turbo_method: :delete } do %>
      <i class="fa-solid fa-arrow-right-from-bracket"></i> <%= t("defaults.logout") %>
    <% end %>
    </div>
  </nav>
  <%# タブレット・PCで展開されるナビゲーションメニュー %>
  <nav class="hidden md:block text-lime-50 w-3/10 h-screen bg-linear-to-r from-blue-600 to-violet-600 fixed top-0 -right-3/10 z-30 transition-all duration-600 text-left text-xl" data-hamburger-target="hamburgerMenu">
    <ul class="py-15">
      <li class="pl-8 lg:pl-16 py-2.5">
        <%= link_to "#" do %>
          <i class="fa-solid fa-circle-info"></i><%= t("defaults.terms_of_use") %>
        <% end %>
      </li>
      <li class="pl-8 lg:pl-16 py-2.5">
        <%= link_to "#" do %>
          <i class="fa-solid fa-circle-info"></i><%= t("defaults.privacy_policy") %>
        <% end %>
      </li>
    </ul>
    <div class="pl-8 lg:pl-16">
      <%= link_to logout_path, data: { turbo_method: :delete } do %>
      <i class="fa-solid fa-arrow-right-from-bracket"></i> <%= t("defaults.logout") %>
    <% end %>
    </div>
  </nav>
  <%# オーバーレイ %>
  <div class="hidden fixed inset-0 bg-black/50 z-20 animate-fade-in-overlay" data-hamburger-target="overlay" data-action="click->hamburger#switchMenu"></div>
  <%# タブレット・PCで常時表示されるナビゲーションメニュー %>
  <nav class="hidden md:flex items-center gap-12 fixed top-5 right-20">
    <ul class="flex items-center gap-4">
      <li>
        <%= link_to root_path do %>
          <i class="fa-regular fa-house"></i> <%= t("defaults.home") %>
        <% end %>
      </li>
      <li>
        <%= link_to cards_path do %>
          <i class="fa-regular fa-file"></i> <%= t("defaults.cards") %>
        <% end %>
      </li>
      <li>
        <%= link_to decks_path do %>
          <i class="fa-regular fa-folder"></i> <%= t("defaults.my_decks") %>
        <% end %>
      </li>
      <li>
        <%= link_to public_decks_path do %>
          <i class="fa-regular fa-folder-open"></i> <%= t("defaults.public_decks") %>
        <% end %>
      </li>
      <li>
        <%= link_to quiz_sessions_path do %>
          <i class="fa-regular fa-circle-question"></i> <%= t("defaults.quiz") %>
        <% end %>
      </li>
    </ul>
  </nav>
</header>