config/routes.rb
Rails.application.routes.draw do
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#home"

  resources :users, only: %i[new create]
  resources :cards, only: %i[index new create edit update destroy]
  resources :decks do
    resources :deck_cards, only: %i[index create destroy]
  end
  resources :public_decks, only: %i[index]
  resources :quiz_sessions, only: %i[index create show destroy] do
    member do
      post :start
      get :question
      post :answer
    end
  end
end

app/models/quiz_session.rb
class QuizSession < ApplicationRecord
  belongs_to :user
  belongs_to :deck
  has_many :answers, dependent: :destroy

  enum status: { pending: 0, in_progress: 1, completed: 2 }

  def answered_cards_ids
    # 既に回答したカードのIDリスト
    self.answers.pluck(:card_id)
  end

  def unanswered_cards
    # まだ回答していないカードを取得するメソッド
    self.deck.cards.where.not(id: answered_cards_ids)
  end

  def random_card
    # ランダムなカードを出題するインスタンスメソッド
    # まだ回答していないカードから出題する

    # カード数が少ない場合はRubyの配列のメソッドであるsampleメソッドで実装してもいい
    # unanswered_cards.sample
    unanswered_cards.order(Arel.sql("RANDOM()")).first
  end

  def answered_count
    # 回答した問題数
    self.answers.count
  end

  def all_answered?
    answered_count >= self.total_questions
  end
end

app/controllers/quiz_sessions_controller.rb
class QuizSessionsController < ApplicationController
  before_action :deck_need_cards, only: %i[create]
  def index
    @quiz_sessions = current_user.quiz_sessions.pending
  end

  def create
    @quiz_session = current_user.quiz_sessions.build(
      deck: @deck,
      total_questions: @deck.cards.count,
      status: :pending
    )
    if @quiz_session.save
      redirect_to quiz_sessions_path, notice: t("defaults.flash_message.reserve_deck_question")
    else
      flash.now[:alert] = t("defaults.flash_message.not_reserve_deck_question")
      render "decks/show", status: :unprocessable_entity
    end
  end

  def destroy
    @quiz_session = current_user.quiz_sessions.find(params[:id])
    @quiz_session.destroy!
    redirect_to quiz_sessions_path, status: :see_other, notice: t("defaults.flash_message.deleted", item: QuizSession.model_name.human)
  end

  def start
    @quiz_session = current_user.quiz_sessions.find(params[:id])
    @quiz_session.update(status: :in_progress)
    redirect_to question_quiz_session_path(@quiz_session)
  end

  def question
    @quiz_session = current_user.quiz_sessions.find(params[:id])

    # 全問回答したら結果ページにリダイレクト
    if @quiz_session.all_answered?
      @quiz_session.update(status: :completed)
      redirect_to quiz_session_path(@quiz_session)
      return
    end

    @random_card = @quiz_session.random_card
  end

  def answer
    # 1問ごとに回答が送信されてくる
    @quiz_session = current_user.quiz_sessions.find(params[:id])
    @card = Card.find(params[:card_id])
    # answerを新規追加する（card_id: @card.id, quiz_session_id: @quiz_session.id, correct: params[:correct]）
    @answer = @quiz_session.answers.build(
      card: @card,
      correct: params[:correct]
    )

    # 回答結果を受け取ったらクイズページにリダイレクト
    if @answer.save
      redirect_to question_quiz_session_path(@quiz_session)
    else
      render :question, status: :unprocessable_entity
    end
  end

  def show
    # 最後の回答が送信された後に表示される結果ページ
    @quiz_session = current_user.quiz_sessions.find(params[:id])
    @answers = @quiz_session.answers
    @incorrect_answers = @answers.where(correct: false)
    @correct_number = @answers.where(correct: true).count
  end

  private

  def deck_need_cards
    @deck = Deck.find(params[:deck_id])
    unless @deck.cards.exists?
      flash.now[:alert] = t("defaults.flash_message.no_cards")
      render "decks/show", status: :unprocessable_entity
    end
  end
end

app/helpers/quiz_sessions_helper.rb
module QuizSessionsHelper
end

app/views/quiz_sessions/_incorrect_answer.html.erb
<div class="border-2 border-blue-500 shadow-sm w-full h-42 shadow-pink-300 rounded-lg p-2">
  <p class="font-bold"><%= incorrect_answer.card.name %></p>
  <p class="mt-1"><%= incorrect_answer.card.meaning %></p>
</div>

app/views/quiz_sessions/_quiz_session.html.erb
<div class="flex flex-col border-2 border-indigo-800 shadow-sm shadow-blue-300 rounded-lg w-full h-[250px] lg:h-[300px] p-2">
  <p>
    <span class="border-b">
      <i class="fa-solid fa-user"></i> <%= quiz_session.deck.user.name %>
    </span>
  </p>
  <p class="font-bold mt-2"><%= quiz_session.deck.name %></p>
  <p class="mt-1"><%= quiz_session.deck.description %></p>
  <div class="mt-auto flex justify-end items-center gap-2">
    <%= button_to start_quiz_session_path(quiz_session), class: "primary-button px-2 py-1" do %>
      <i class="fa-solid fa-circle-play"></i> <%= t("defaults.start_quiz") %>
    <% end %>
    <%= button_to quiz_session_path(quiz_session), class: "red-button px-2 py-1", method: :delete, data: { turbo_confirm: t('defaults.delete_confirm') } do %>
      <i class="fa-solid fa-folder-minus"></i> <%= t("defaults.quit_quiz") %>
    <% end %>
  </div>
</div>

app/views/quiz_sessions/index.html.erb
<% set_meta_tags title: t(".title") %>
<div class="page-container mt-24 mb-18 md:mb-8 px-6 md:px-10 lg:px-16 py-4 md:py-8">
  <h1 class="font-bold text-2xl md:text-3xl lg:text-4xl mb-4 text-center">
    <span class="border-b-2"><%= t(".title") %></span>
  </h1>
  <div class="font-bold text-lg md:text-xl mb-4 text-center">
    <i class="fa-solid fa-square-plus"></i>
    <%= t(".add_decks_html", my_decks: link_to(t("defaults.my_decks"), decks_path, class: "text-indigo-500 border-b border-dashed"), public_decks: link_to(t("defaults.public_decks"), public_decks_path, class: "text-indigo-500 border-b border-dashed") ) %>
  </div>
  <% if @quiz_sessions.exists? %>
    <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-2 md:gap-4">
      <%= render @quiz_sessions %>
    </div>
  <% end %>
</div>

app/views/quiz_sessions/question.html.erb
<% set_meta_tags title: t(".title") %>
<% content_for(:title, t(".title")) %>
<div class="page-container mt-24 mb-18 md:mb-8 px-6 md:px-10 lg:px-16 py-4 md:py-8" data-controller="answer">
  <h1 class="font-bold text-3xl md:text-4xl">
    <i class="fa-regular fa-circle-question"></i><%= @quiz_session.deck.name %>
  </h1>
  <div class="flex flex-col items-center gap-4 bg-violet-100 mt-2 md:mt-4 p-4 md:p-6">
    <h2 class="font-bold text-xl md:text-2xl"><%= t(".quiz_number", number: @quiz_session.answered_count + 1) %></h2>
    <p class="font-medium text-2xl md:text-3xl border-b">
      <span class="animate-fade-in"><%= @random_card.name %></span>
    </p>
    <button class="primary-button px-2 py-1" data-answer-target="showAnswer" data-action="click->answer#switchButton"><i class="fa-regular fa-eye"></i> <%= t(".show_answer") %></button>
    <div class="hidden flex flex-col items-center" data-answer-target="answerButton">
      <div class="text-indigo-500">
        <i class="fa-solid fa-circle-check"></i><%= @random_card.meaning %>
      </div>
      <div class="flex gap-2 mt-4 md:mt-6">
        <%= button_to answer_quiz_session_path(@quiz_session), { class: "green-button px-4 py-1", method: :post, params: { correct: true, card_id: @random_card.id } } do %>
          <i class="fa-regular fa-face-smile-beam"></i> <%= t(".correct") %>
        <% end %>
        <%= button_to answer_quiz_session_path(@quiz_session), { class: "red-button px-2 py-1", method: :post, params: { correct: false, card_id: @random_card.id } } do %>
          <i class="fa-regular fa-face-dizzy"></i> <%= t(".incorrect") %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/quiz_sessions/show.html.erb
<% set_meta_tags title: t(".title") %>
<div class="page-container mt-24 mb-8 px-2 md:px-10 lg:px-16 py-4 md:py-8">
  <div class="flex justify-between">
    <h1 class="font-bold text-3xl md:text-4xl">
      <i class="fa-solid fa-bullhorn"></i><%= t(".title") %>
    </h1>
    <%= button_to quiz_sessions_path(deck_id: @quiz_session.deck.id), { method: :post, class: "text-center primary-button px-2 md:px-4 py-2" } do %>
      <i class="fa-solid fa-folder-plus"></i> <%= t(".retry") %>
    <% end %>
  </div>
  <p class="font-bold text-xl my-2"><%= t(".result", total_questions: @quiz_session.total_questions, correct_number: @correct_number) %></p>
  <div class="bg-violet-100 p-2">
    <h2 class="font-bold text-2xl text-center"><%= t(".result_detail") %></h2>
    <div class="mt-2">
      <div class="text-center">
        <span class="border-b">
          <i class="fa-solid fa-user"></i> <%= @quiz_session.deck.user.name %>
        </span>
        <div class="font-bold">
          <%= @quiz_session.deck.name %>
        </div>
      </div>
      <div class="grid grid-cols-[40px_auto_40px] md:w-2/3 lg:w-1/3 border mx-auto text-center">
        <p class="font-bold border-r">No.</p>
        <p class="font-bold border-r"><%= t(".card_name") %></p>
        <p class="font-bold"><%= t(".correctness") %></p>
        <% @answers.each_with_index do |answer, index| %>
          <div class="border-r border-t"><%= index + 1 %></div>
          <div class="border-r border-t"><%= answer.card.name %></div>
          <div class="border-t">
            <%= answer.correct ? t(".correct") : t(".incorrect") %>
          </div>
        <% end %>
    </div>
    <h3 class="font-bold text-lg mt-4 text-center"><%= t(".incorrect_cards") %></h3>
    <% if @incorrect_answers.exists? %>
      <div class="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-2">
        <% @incorrect_answers.each do |incorrect_answer| %>
          <%= render "incorrect_answer", incorrect_answer: incorrect_answer %>
        <% end %>
      </div>
    <% else %>
      <div class="text-lime-600 text-center">
        <i class="fa-solid fa-circle-check"></i> <%= t(".all_correct_message") %>
      </div>
    <% end %>
  </div>
</div>