config/routes.rb
Rails.application.routes.draw do
  get "login", to: "user_sessions#new"
  post "login", to: "user_sessions#create"
  delete "logout", to: "user_sessions#destroy"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
  root "static_pages#home"

  resources :users, only: %i[new create]
  resources :cards, only: %i[index new create edit update destroy]
  resources :decks do
    resources :deck_cards, only: %i[index create destroy]
  end
  resources :public_decks, only: %i[index]
  resources :quiz_sessions, only: %i[index create show destroy] do
    member do
      post :start
      get :question
      post :answer
    end
  end
end

app/models/deck.rb
class Deck < ApplicationRecord
  validates :name, presence: true, length: { maximum: 36 }
  validates :description, length: { maximum: 72 }
  validates :public, inclusion: [ true, false ]

  belongs_to :user
  has_many :deck_cards, dependent: :destroy
  has_many :cards, through: :deck_cards
  has_many :quiz_sessions, dependent: :destroy
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index
    @decks = current_user.decks
  end

  def new
    @deck = Deck.new
  end

  def create
    @deck = current_user.decks.build(deck_params)
    if @deck.save
      redirect_to deck_path(@deck), notice: t("defaults.flash_message.created", item: Deck.model_name.human)
    else
      flash.now[:alert] = t("defaults.flash_message.not_created", item: Deck.model_name.human)
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @deck = current_user.decks.find(params[:id])
  end

  def edit
    @deck = current_user.decks.find(params[:id])
  end

  def update
    @deck = current_user.decks.find(params[:id])
    if @deck.update(deck_params)
      redirect_to deck_path(@deck), notice: t("defaults.flash_message.updated", item: Deck.model_name.human)
    else
      flash.now[:alert] = t("defaults.flash_message.not_updated", item: Card.model_name.human)
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    deck = current_user.decks.find(params[:id])
    deck.destroy!
    redirect_to decks_path, status: :see_other, notice: t("defaults.flash_message.deleted", item: Deck.model_name.human)
  end

  private

  def deck_params
    params.require(:deck).permit(:name, :description, :public)
  end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_deck.html.erb
<div class="flex flex-col border-2 border-indigo-800 shadow-sm shadow-blue-300 rounded-lg w-full h-[200px] p-2">
  <p class="font-bold"><%= deck.name %></p>
  <p class="mt-1"><%= deck.description %></p>
  <div class="mt-auto flex items-center justify-between">
    <% if deck.public %>
      <i class="fa-solid fa-lock-open"></i>
    <% else %>
      <i class="fa-solid fa-lock"></i>
    <% end %>
    <div class="mt-auto flex justify-end items-center gap-1 md:gap-2">
      <% if deck_page == "show" %>
        <%= link_to deck_deck_cards_path(deck), class: "blue-button px-1 md:px-2 py-0.5" do %>
          <i class="fa-solid fa-circle-plus"></i> <%= t("defaults.link.to_add_card_page") %>
        <% end %>
      <% else%>
        <%= button_to quiz_sessions_path(deck_id: deck.id), { method: :post, class: "primary-button px-0.5 md:px-2 py-0.5" } do %>
          <i class="fa-solid fa-folder-plus"></i> <%= t("defaults.question_reservation") %>
        <% end %>
        <%= link_to deck_path(deck), class: "blue-button px-0.5 md:px-2 py-0.5" do %>
          <i class="fa-solid fa-eye"></i> <%= t("defaults.show") %>
        <% end %>
      <% end %>
      <%= link_to edit_deck_path(deck), class: "green-button px-0.5 md:px-2 py-0.5" do %>
        <i class="fa-solid fa-file-pen"></i> <%= t("defaults.edit") %>
      <% end %>
      <%= button_to deck_path(deck), class: "red-button px-0.5 md:px-2 py-0.5", method: :delete, data: { turbo_confirm: t("defaults.delete_confirm") } do %>
        <i class="fa-solid fa-trash-can"></i> <%= t("defaults.delete") %>
      <% end %>
    </div>
  </div>
</div>

app/views/decks/_deck_cards.html.erb
<div class="flex flex-col border-2 border-blue-500 shadow-sm shadow-pink-300 rounded-lg w-full h-[150px] p-2">
  <p class="font-bold"><%= card.name %></p>
  <p class="mt-1"><%= card.meaning %></p>
  <div class="mt-auto text-right">
    <%= button_to deck_deck_card_path(deck, deck.deck_cards.find_by(card_id: card.id)), class: "red-button px-1 md:px-2 py-0.5", method: :delete, data: { turbo_confirm: t('defaults.delete_confirm') } do %>
      <i class="fa-solid fa-circle-minus"></i> <%= t("defaults.delete_from_deck") %>
    <% end %>
  </div>
</div>

app/views/decks/_form.html.erb
<%= form_with model: @deck do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <%= f.label :name, class: "block mt-3" %>
  <%= f.text_field :name, class: "bg-white border border-indigo-300 w-full mt-2 px-2 py-1" %>

  <%= f.label :description, class: "block mt-3" %>
  <%= f.text_area :description, class: "bg-white border border-indigo-300 w-full h-27 md:h-21 mt-2 px-2 py-1" %>

  <p class="mt-3"><%= t("defaults.public.config") %></p>
  <div class="mt-2">
    <%= f.radio_button :public, true %>
    <%= f.label :public_true do %>
      <%= t("defaults.public.true") %><i class="fa-solid fa-unlock"></i>
    <% end %>

    <span class="mx-1"></span>

    <%= f.radio_button :public, false %>
    <%= f.label :public_false do %>
      <%= t("defaults.public.false") %><i class="fa-solid fa-lock"></i>
    <% end %>
  </div>

  <%= f.submit class: "primary-button block mx-auto mt-4 px-6 py-1.5" %>
<% end %>

app/views/decks/edit.html.erb
<% set_meta_tags title: t(".title") %>
<div class="page-container w-full md:w-2/3 lg:w-2/5 mx-auto mt-24 mb-8 px-6 md:px-10 py-6">
  <h1 class="font-bold text-2xl md:text-3xl lg:text-4xl text-center"><%= t(".title") %></h1>
  <%= render 'form', deck: @deck %>
</div>

app/views/decks/index.html.erb
<% set_meta_tags title: t(".title") %>
<div class="page-container mt-24 mb-18 md:mb-8 px-2 md:px-24 lg:px-16 py-4 md:py-8">
  <div class="font-bold mb-4">
    <div class="flex items-center justify-center gap-2 md:gap-4 mb-4">
      <h1 class="text-2xl md:text-3xl lg:text-4xl border-b-2"><%= t(".title") %></h1>
      <%= link_to t(".to_public_decks_page"), public_decks_path, class: "text-indigo-400 text-xl md:text-2xl" %>
    </div>
    <div class="text-center">
      <%= link_to new_deck_path, class: "text-indigo-500 text-xl md:text-2xl border-b-1 border-dashed" do %>
        <i class="fa-solid fa-square-plus"></i><%= t(".to_create_deck_page") %>
      <% end %>
    </div>
  </div>
  <% if @decks.present? %>
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-4 lg:gap-6">
      <% @decks.each do |deck| %>
        <%= render 'deck', deck: deck, deck_page: "index" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/decks/new.html.erb
<% set_meta_tags title: t(".title") %>
<div class="page-container w-full md:w-2/3 lg:w-2/5 mx-auto mt-24 mb-8 px-6 md:px-10 py-6">
  <h1 class="font-bold text-2xl md:text-3xl lg:text-4xl text-center"><%= t(".title") %></h1>
  <%= render 'form', deck: @deck %>
</div>

app/views/decks/show.html.erb
<% set_meta_tags title: t(".title") %>
<div class="page-container w-full lg:w-2/3 mx-auto mt-24 mb-18 md:mb-8 px-2 md:px-10 py-6">
  <div class="flex justify-between items-center mb-3">
    <h1 class="font-bold text-xl md:text-2xl lg:text-3xl"><%= t(".title") %></h1>
    <%= button_to quiz_sessions_path(deck_id: @deck.id), { method: :post, class: "primary-button px-4 py-2" } do %>
      <i class="fa-solid fa-folder-plus"></i> <%= t("defaults.question_reservation") %>
    <% end %>
  </div>
  <%= render 'decks/deck', deck: @deck, deck_page: "show" %>
  <div class="font-bold text-lg mt-4 mb-2"><%= t(".added_cards") %></div>
  <% if @deck.cards.exists? %>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-2 w-full">
      <% @deck.cards.each do |card| %>
        <%= render 'decks/deck_cards', deck: @deck, card: card %>
      <% end %>
    </div>
  <% else %>
    <div class="text-red-500">
      <i class="fa-solid fa-circle-exclamation"></i> <%= t(".no_cards") %>
    </div>
  <% end %>
</div>